DASH_APP:
  APP_TITLE: Rainfall Data Explorer
  UPDATE_TITLE: Updating...
  DEBUG: FALSE

DASH_THEME:
  THEME: ZEPHYR

TEMPLATE:
  LOGO_SOURCE: 
  WATERMARK_SOURCE: 
  SHOW_LEGEND_INSIDE: False
  SHOW_RANGESELECTOR: False

VERSION: v1.4.0
GITHUB_LINK: https://github.com/taruma/rainfall
GITHUB_REPO: taruma/rainfall
